server:
  port: 80
spring:
  datasource:
    username: cart
    password: deadl1ne
    url: jdbc:mysql://cart-db:3306/cart?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
